---
title: "Risk Adjusted Outcomes for Urologic Oncology"
subtitle: "OSHPD Data Descriptions"
author: "Anobel Y Odisho, Ruth Etzioni, John L Gore"
date: "`r Sys.Date()`"
output: 
  tufterhandout::html_tufte_handout:
        theme: cosmo
        css: floating.css
        toc: yes
params:
    cohort: "RP"
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, fig.width=12, cache=T)
```
?knitr
<!--- this inline CSS style is to alter horizontal table padding for stargazer tables -->
<style>
  td {
    padding-left: 3px;
    padding-right: 3px;
  }
</style>
  

```{r packages, cache=F}
# Data Cleaning Packages
library(lubridate)
library(plyr)
library(dplyr)
library(stringr)
library(tidyr)

# Graphics Packages
library(DT)
library(ggplot2)
library(ggthemes)
library(knitr)
library(RColorBrewer)
library(stargazer)

# Specialty Packages
library(icd9)
```

```{r constants.functions}
bg <- "#FCFCFA"
main1 <- "#ca0020"
acc1 <- "#f4a582"
main2 <- "#92c5de"
acc2 <- "#0571b0"

# this function takes arguments x=value, y=number of sig figs, prints mean +/- SD in html
prettyMeanSD <- function (x,y) {
  mean <- prettyNum(round(mean(x, na.rm=TRUE),y), big.mark = ",")
  sd <-  prettyNum(round(sd(x, na.rm=TRUE),y), big.mark = ",")
  paste(mean, " &plusmn; ",sd,sep="")
}

prettyMedianIQR <- function (x,y) {
  median <- prettyNum(round(median(x, na.rm=TRUE),y), big.mark = ",")
  tiles <- round(quantile(x, c(.25, .75), na.rm=TRUE),y)
  paste(median, " (",tiles[1], " - ", tiles[2], ")",sep="")
}
```

```{r loaddata}
# Load full dataset (12.5m obs)
# when loading the full data set, in chunk options set cache.lazy=F
# load(file="rao_workingdata/pt.rda")

# Load lite dataset (sample of 100,000 obs)
load(file="rao_workingdata/ptlite.rda")
pt <- pt[year(pt$admtdate)>2005,] # take out after next run of main data
```

# Overall Summary
- Total Records: `r nrow(pt)`
- Records in GU specific cohort `r nrow(ptgu)`

```{r fields, cache=F}
datatable(as.data.frame(names(pt)))
```

# Admission Dates
Overall Cohort
```{r}
pt %>%
  ggplot(aes(x=admtdate)) + 
  geom_histogram(fill=main2, color="white") + 
  theme_few() +
  theme(plot.background = element_rect(fill=bg), 
        legend.background= element_rect(fill=bg), 
        legend.title=element_blank()) + 
  labs(title="Admission Date Distribution, Entire Cohort", 
       y="Number of Admissions", 
       x="Admission Date")
```

Overall GU Cohort
```{r}
kable(t(table(ptgu$cohort)))

ptgu %>%
  ggplot(aes(x=admtdate, weight=1)) + 
  # geom_histogram(aes(y=..density..), fill=main2, alpha=0.3, color="white") +
  geom_density(aes(y=..count.., color=cohort)) +
  scale_color_brewer(palette = "Dark2") + 
  theme_few() +
  theme(plot.background = element_rect(fill=bg), 
        legend.background= element_rect(fill=bg), 
        legend.title=element_blank()) + 
  labs(title="Admission Dates for GU Cohort", 
       y="Number of Admissions", 
       x="Admission Date")
```

# Readmissions
Overall 30 day Readmission Rate (%)
```{r, results="asis"}
t1 <- round(100*prop.table(table(pt$isreadmit)),2)
t2 <- round(100*prop.table(table(ptgu$isreadmit, ptgu$cohort),2),2)
t <- as.data.frame(cbind(t1, t2))
colnames(t)[1] <- "All Patients"
stargazer(t, summary=F, type="html", digits = 2)
```

# Disposition
Overall Disposition Distribution (%)
```{r, results="asis"}
t1 <- round(100*prop.table(table(pt$disp)), 2)
t2 <- round(100*prop.table(table(ptgu$disp, ptgu$cohort),2),2)

t <- as.data.frame(cbind(t1, t2))
colnames(t)[1] <- "All Patients"
stargazer(t, summary=F, type="html", digits = 2, digits.extra = 2)
```

# Race/Ethnicity
(%)
```{r, results="asis"}
t1 <- round(100*prop.table(table(pt$race_grp)), 2)
t2 <- round(100*prop.table(table(ptgu$race_grp, ptgu$cohort),2),2)

t <- as.data.frame(cbind(t1, t2))
colnames(t)[1] <- "All Patients"
stargazer(t, summary=F, type="html", digits = 2, digits.extra = 2)
```

# Payers
Payer Category (%)
```{r, results="asis"}
t1 <- round(100*prop.table(table(pt$pay_cat)), 2)
t2 <- round(100*prop.table(table(ptgu$pay_cat, ptgu$cohort),2),2)

t <- as.data.frame(cbind(t1, t2))
colnames(t)[1] <- "All Patients"
stargazer(t, summary=F, type="html")
```
<br>

Payer Type (%)
```{r, results="asis"}
t1 <- round(100*prop.table(table(pt$pay_type)), 2)
t2 <- round(100*prop.table(table(ptgu$pay_type, ptgu$cohort),2),2)

t <- as.data.frame(cbind(t1, t2))
colnames(t)[1] <- "All Patients"
stargazer(t, summary=F, type="html")
```

```{r}
